from typing import Any, Mapping, Sequence
from .otel import TurnDbSpanExporter, map_normalized_span, map_readable_span, trace_gen_ai_call, trace_gen_ai_call_async

class TurnDbError(Exception): ...
class InvalidArgumentError(TurnDbError): ...
class NotFoundError(TurnDbError): ...
class CorruptionError(TurnDbError): ...
class CancelledError(TurnDbError): ...
class UnsupportedError(TurnDbError): ...
class BusyError(TurnDbError): ...
class ClosedError(TurnDbError): ...

def capabilities() -> dict[str, Any]: ...

class Snapshot:
    @staticmethod
    def open(path: str) -> Snapshot: ...
    def scan(self, request: Mapping[str, Any]) -> dict[str, Any]: ...
    def explain_scan(self, request: Mapping[str, Any]) -> dict[str, Any]: ...
    def read_content(self, id: str, name: str) -> bytes | None: ...
    def schema(self) -> dict[str, Any]: ...
    def close(self) -> None: ...

class Store:
    @staticmethod
    def open(path: str, *, queue_capacity: int = 64) -> Store: ...
    def write(self, operations: Sequence[Mapping[str, Any]], *, durable: bool = False) -> dict[str, Any]: ...
    def sync(self) -> None: ...
    def flush(self) -> bool: ...
    def backup(self, path: str) -> dict[str, str]: ...
    def scan(self, request: Mapping[str, Any]) -> dict[str, Any]: ...
    def explain_scan(self, request: Mapping[str, Any]) -> dict[str, Any]: ...
    def read_content(self, id: str, name: str) -> bytes | None: ...
    def snapshot(self) -> Snapshot: ...
    def schema(self) -> dict[str, Any]: ...
    def verify(self) -> dict[str, Any]: ...
    def space_usage(self) -> dict[str, Any]: ...
    def compact_bounded(self, *, max_input_parts: int, max_input_rows: int, max_input_bytes: int) -> dict[str, Any]: ...
    def refold(self) -> dict[str, Any]: ...
    def erase(self, ids: Sequence[str]) -> dict[str, Any]: ...
    def close(self, *, durable: bool = False) -> None: ...
