from typing import Any, Awaitable, Callable, Iterable, Mapping, TypeVar
from . import Store

T = TypeVar("T")

def map_normalized_span(span: Mapping[str, Any]) -> dict[str, Any]: ...
def map_readable_span(span: Any) -> dict[str, Any]: ...
def trace_gen_ai_call(tracer: Any, call: Callable[[], T], *, operation_name: str,
                      provider_name: str | None = None, model: str | None = None,
                      span_name: str | None = None, input_messages: Any = None,
                      output_messages: Any | Callable[[T], Any] = None,
                      attributes: Mapping[str, Any] | None = None) -> T: ...
async def trace_gen_ai_call_async(tracer: Any, call: Callable[[], Awaitable[T]], *, operation_name: str,
                                  provider_name: str | None = None, model: str | None = None,
                                  span_name: str | None = None, input_messages: Any = None,
                                  output_messages: Any | Callable[[T], Any] = None,
                                  attributes: Mapping[str, Any] | None = None) -> T: ...

class TurnDbSpanExporter:
    def __init__(self, path_or_store: str | Store, *, durable_every_export: bool = True,
                 flush_every_spans: int = 512, flush_interval_seconds: float = 5.0) -> None: ...
    def export(self, spans: Iterable[Any]) -> Any: ...
    def force_flush(self, timeout_millis: int = 30000) -> bool: ...
    def shutdown(self) -> None: ...
